name: Audit pull request
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'open-sauced.netlify.app'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
